Bringup UAT preamble locks and fix issues with 0.8.0 (#99)
* Improve Coprocessor SPI bus and OTA

* Consolidate network console messages to larger blobs to avoid hogging the bus with teeny transactions.
* Allow SPIBeginTransaction to exit wait if received and expected handshake.
* Add websocket close/open to OTA retry behavior.

* Fix decoder segfault and remove unised Pico SDK folder

* Add safe conversion function to fix undefined behavior when casting negative floats to uint32_t

* GCC upgrade in development environment changed handling of casts from negative float to uint32_t. Added a convenience function that explicitly converts a float to a positive value before casting and then two's complementing as necessary to avoid issues when converting a negative float that is close to the max resolution of a UINT32_T.

* Fix duplicate message filter

* Make startup behavior compatible with m1090 and 1090U Rev B.

* Limit OTA write chunk attempts and improve on-device unit tests

* Add additional repetitions of MLAT timing tests.
* Improve CC1312 guards in tests.

* Add __time_critical_func to timestamping functions to try fixing MLAT (didn't work)

* First pass at MLAT jitter correction with PWM counter and DMA

* De-skew MLAT timestamps and get MALT working!!

* Change mlat jitter count array to single value

* Move network settings out of CommsManager

* WIP add core network settings restore

* Add core network settings unit test and fix checksum issue

* Change whereplane.xyz feed to active by default, up-rev settings, fix ESP32 firmware, RC7

* Get code building on pico after ESP32 fixes

* Fix ESP32 initialization

* WIP setting up SPI stuff

* WIP make things compile

* Get TI code compiling with ported coprocessor driver

* WIP save progress before consolidating coprocessor master code

* WIP weird hardfault error

* WIP fixed hardfault, CC1312 getting talked to but not responding

* WIP SPI driver

* Add SVD file to TI workspace.
* Get SPI lockout working properly for CC1312.
* CC1312 responding to transactions but only the first Byte.
* Get settings to persist subg enable.

* Save progress before migrating to FreeRTOS

* Switch SPI polarity and phase to CPHA=1 CPOL=1 to make TI MCU happy

* WIP getting freertos to compile

* WIP maybe SPI working, DMA interrupt was shadowning SPI complete interrupt

* SPI transfers working, do a little cleanup

* CC1312 is talking!

* CC1312 status polling working

* WIP debugging prints and early handshake exits

* Fix issue with spi coprocessor update rates

* Move update rate stuff into coprocessor parent class so we don't have issues with the lower level interface updating when the main coprocessor object isn't reading it (this was causing a bunch of empty log messages to be read out and printed since the upper level driver was printing logs based on stale info).

* Improve CC1312 enable / disable timing logic

* Fix extra log prints during CC1312 startup

* Update sync word

* Rx working with generous preamble!

* Add new enclosure files and fix baud rate and reporting protocol settings apply

* Fix issue that was trying subg radio updates when hardware not equipped

* Add print files for FPVToys display cockpit

* Fix unit tests

* Remove undefined reference to UpdateLED on host.